spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  mail:
    host: smtp.gmail.com
    port: 587
    username: vovasamb999@gmail.com
    password: jgicfgwgcsdqhnmd
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
      mail:
        smtp:
          starttls:
            enable: true
  messages:
    basename: messages

app:
  locale: ru
